//! Internal benchmark: `cargo test --release -p snell-protocol
//! profile::bench::fill_baseline -- --ignored --nocapture --test-threads=1`.
//! Test-only access keeps profiling methods out of the production API.

use std::hint::black_box;
use std::time::{Duration, Instant};

use super::*;

#[path = "../../benches/support/profile_cases.rs"]
mod profile_cases;

const LENGTHS: [usize; 4] = [32, 128, 512, 1460];
const SEQUENCES: usize = 256;
const REPETITIONS: usize = 6;

fn checksum(bytes: &[u8], initial: u64) -> u64 {
    bytes.iter().fold(initial, |hash, &byte| {
        (hash ^ u64::from(byte)).wrapping_mul(0x100000001b3)
    })
}

fn corpus_hash(profile: &Profile) -> u64 {
    let mut hash = 0xcbf29ce484222325;
    let mut output = [0u8; 1460];
    for seq in [0, 1, 7, 255, u32::MAX] {
        for len in [0, 1, 7, 8, 9, 32, 128, 512, 1460] {
            profile.fill_official(seq, &mut output[..len]);
            hash = checksum(&output[..len], hash);
        }
    }
    hash
}

#[test]
fn profile_cases_match_baseline() {
    let expected = [
        0xbb0859fbf4284572,
        0x6f4d518106f378a1,
        0xda4ed6c4936496dd,
        0x717144ff964870fe,
    ];
    for (generator, key) in profile_cases::CASES {
        let profile = Profile::derive(key).unwrap();
        assert_eq!(profile.generator, generator);
        assert_eq!(corpus_hash(&profile), expected[generator as usize]);
    }
}

fn run(profile: &Profile, output: &mut [u8], iterations: usize) -> Duration {
    let started = Instant::now();
    for index in 0..iterations {
        // Repeat an identical sequence corpus in every sample and prevent both
        // input specialization and dead-store elimination of any generated byte.
        black_box(profile).fill_official(
            black_box((index % SEQUENCES) as u32),
            black_box(&mut *output),
        );
        black_box(&*output);
    }
    started.elapsed()
}

#[test]
#[ignore = "performance measurement; run alone in release mode"]
fn fill_baseline() {
    profile_cases_match_baseline();
    println!(
        "debug_assertions={} (baseline requires false)",
        cfg!(debug_assertions)
    );
    let profiles = profile_cases::CASES.map(|(generator, key)| {
        let profile = Profile::derive(key).unwrap();
        assert_eq!(profile.generator, generator);
        profile
    });
    // Derivation, allocation, warmup and calibration are outside samples.
    let mut output = [0u8; 1460];
    let mut counts = [[SEQUENCES; LENGTHS.len()]; 4];
    for (generator, profile) in profiles.iter().enumerate() {
        for (size, &len) in LENGTHS.iter().enumerate() {
            let iterations = &mut counts[generator][size];
            run(profile, &mut output[..len], SEQUENCES);
            while run(profile, &mut output[..len], *iterations) < Duration::from_millis(50) {
                *iterations *= 2;
                assert!(*iterations <= 1 << 26, "calibration exceeded bound");
            }
        }
    }
    println!("generator,length,repetition,iterations,elapsed_ns,ns_per_call,output_hash");
    for repetition in 0..REPETITIONS {
        // Rotate and reverse case order; repetition zero is not in the summary.
        for offset in 0..16 {
            let case = if repetition % 2 == 0 {
                offset
            } else {
                15 - offset
            };
            let case = (case + repetition * 3) % 16;
            let generator = case / LENGTHS.len();
            let size = case % LENGTHS.len();
            let len = LENGTHS[size];
            let iterations = counts[generator][size];
            let elapsed = run(&profiles[generator], &mut output[..len], iterations);
            println!(
                "{generator},{len},{repetition},{iterations},{},{:.3},{:016x}",
                elapsed.as_nanos(),
                elapsed.as_nanos() as f64 / iterations as f64,
                checksum(&output[..len], 0xcbf29ce484222325)
            );
        }
    }
}
