[workspace]
changelog_config = "cliff.toml"
changelog_update = true
dependencies_update = false
git_only = true
git_release_enable = true
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
repo_url = "https://github.com/ShinyNito/snell-rs"

[[package]]
name = "snell-rs"
changelog_path = "CHANGELOG.md"
git_release_enable = true
git_tag_name = "v{{ version }}"
publish = false
