[package]
name = "snell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Snell client/server binary"

[[bin]]
name = "snell-rs"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
snell-config = { path = "../snell-config", version = "0.0.0" }
snell-runtime = { path = "../snell-runtime", version = "0.0.0" }
