[package]
name = "snell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Snell client/server binary"

[[bin]]
name = "snell-rs"
path = "src/main.rs"

[features]
default = []
unsafe-raw = ["snell-runtime/unsafe-raw"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
snell-config = { path = "../snell-config", version = "0.0.0" }
snell-runtime = { path = "../snell-runtime", version = "0.0.0" }
tracing.workspace = true
tracing-subscriber.workspace = true
tokio = { workspace = true, features = [
  "io-util",
  "macros",
  "net",
  "rt-multi-thread",
  "signal",
  "time",
] }

[dev-dependencies]
snell-testkit = { path = "../snell-testkit", version = "0.0.0" }
tokio = { workspace = true, features = [
  "io-util",
  "macros",
  "net",
  "process",
  "rt-multi-thread",
  "sync",
  "time",
] }
